---
title: "R Notebook"
output: html_notebook
---
 intermediate R
 
```{r}
3 == (2 + 1)
"intermediate" != "r"
TRUE != FALSE
"Rchitect" != "rchitect"

```

greater and ess than

```{r}
-6*5+2 >= -10+1

"raining" <= "table"
TRUE > FALSE


```
COMPARE VECTORS and matrices
```{r}
linkedin <- c(16,9,13,5,2,17,14)
facebook <- c(17,7,5,16,8,13,14)


linkedin > 15 
facebook <= 10

linkedin > facebook

views <- matrix(c(linkedin,facebook), nrow = 2, byrow = TRUE)

views == 13
views <=14

```

operator logical
```{r}

linkedin <= 10 & facebook == 13

linkedin <= 10 | facebook == 13
views >11 & views <=14

```

the if statement
```{r}
medium <- "linkedin"
num_views <- 14

if (medium == "linkedin"){print("showing linkedIn information")
  }else {
  print("unknown medium")
  }

if (num_views >15){
  print("youre popuar")
}else{
  print("try to be more visibe")
}


```

customize further : ese if


```{r}
if (medium == "linkedin")
  {print("showing linkedIn information")
  } else if(medium == "facebook"){
  print("Show facebook information")
  }

```
else 2.0

```{r}
number <- 6
result <-""

if (number < 10) {
  if (number < 5 ){
    result <- "extra small"
    
  }
 
else{
   result <- "small"
}
}else if (number < 100){ 
  result <- "medium"
} else {
  result <- "large"
}
 
print(result)


```




loops

```{r}
speed <- 64

while (speed >30) {
  print( paste("slow down big time",speed) )
  

  
  if(speed >=48){
    print("slow down bit time")
  speed <- speed - 11
  }else {
    print("slow down")
     speed <- speed - 6
  }
  
  
  
  
}
speed
```

```{r}

speed <- 88

while (speed >30) {
  print( paste("slow down big time",speed) )
  
  if(speed >80){
    break
  }
  
  if(speed >=48){
    print("slow down bit time")
  speed <- speed - 11
  }else {
    print("slow down")
     speed <- speed - 6
  }
  
  
  
  
}
speed

```

```{r}
linkedin <- c(16,9,13,5,2,17,14)
for (l in linkedin) {
  print(l)
  
  
for (i in 1: length(linkedin) ) {
  print(linkedin[i])
}  
}
```


```{r}
nyc <- list(pop= 8405837,boroughs=c("manhattan","bronx","brooklyn","queens","starten island"), capital=FALSE )

for (n in nyc) {
  print(n)
  
}

for (i in 1: length(nyc)) {
  if(i==2){
      for (j in 1: length(nyc[[i]])) {
    print(nyc[[i]][j])
      }
         }else{
  print(nyc[[i]])
  
}
}


```


```{r}
views <- matrix(c(linkedin,facebook), nrow = 2, byrow = TRUE)

for (row in 1: nrow(views)) {
  for (col in 1: ncol(views) ){
    print(paste("on row", row, "and column", col, "contanins", views[row,col] ))
    
    
  }
  
}
```

 
 